apiVersion: apps/v1
kind: Deployment
metadata:
  name: child-app2
  namespace: child-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: child-app2
  template:
    metadata:
      labels:
        app: child-app2
    spec:
      containers:
      - name: child-app2
        image: nginx:latest
        ports:
        - containerPort: 80
