apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: parent-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cluster1
            url: https://kubernetes.default.svc
          - cluster: cluster2
            url: https://127.0.0.1:52936
    - git:
        repoURL: https://github.com/andres-mccree/andres-proj
        revision: HEAD
        directories:
          - path: apps/child-app1
          - path: apps/child-app2
  template:
    metadata:
      name: '{{.cluster}}-{{path.basename}}-app'
      labels:
        environment: production
        app: parent-app
    spec:
      project: default
      source:
        repoURL: 'https://github.com/andres-mccree/andres-proj'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
