apiVersion: apps/v1
kind: Deployment
metadata:
  name: child-app1
  namespace: child-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: child-app1
  template:
    metadata:
      labels:
        app: child-app1
    spec:
      containers:
      - name: child-app1
        image: nginx:latest
        ports:
        - containerPort: 80
