# Parent Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/andres-mccree/andres-proj'
    targetRevision: HEAD
    path: apps/parent-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
# Child Application 1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app1
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/andres-mccree/andres-proj'
    targetRevision: HEAD
    path: apps/child-app1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
# Child Application 2
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app2
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/andres-mccree/andres-proj'
    targetRevision: HEAD
    path: apps/child-app2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

